---
vdonf: https://library.oregonstate.edu/floormaps/microforms
vlcv: http://library.oregonstate.edu/reference
vmeg: https://library.oregonstate.edu/floormaps/media-collection
vmes: https://library.oregonstate.edu/floormaps/media-collection
osuo:
curi: https://library.oregonstate.edu/floormaps/newspapers
tgeg: http://osulibrary.oregonstate.edu/borrowing/requesting
slong:
sshort:
vnb: https://library.oregonstate.edu/floormaps/new-books
test:
vurw: https://osulibrary.oregonstate.edu/map/undergraduate-research-and-writing-studio
vge: http://library.oregonstate.edu/floormap-valley-main
vbin:
vctn:
vczg: https://library.oregonstate.edu/floormaps/circulation
vcik: https://library.oregonstate.edu/floormaps/circulation
vcp: https://library.oregonstate.edu/floormaps/compact-collection
vdog: https://library.oregonstate.edu/floormaps/government-documents
vdolc: https://library.oregonstate.edu/floormaps/government-documents
vdnnf: https://library.oregonstate.edu/floormaps/microforms
vdzn: https://library.oregonstate.edu/floormaps/government-documents
vdpn: https://library.oregonstate.edu/floormaps/government-documents
vmhn: https://library.oregonstate.edu/floormaps/maps
vofn:
vmpg: https://library.oregonstate.edu/floormaps/maps
vmrn: https://library.oregonstate.edu/floormaps/maps-reference
vman: https://library.oregonstate.edu/floormaps/maps
vmzn: https://library.oregonstate.edu/floormaps/maps
vmpu: https://library.oregonstate.edu/floormaps/maps
vmsn:
vmin: https://library.oregonstate.edu/floormaps/microforms
vminr: https://library.oregonstate.edu/floormaps/microforms
vminf: https://library.oregonstate.edu/floormaps/microforms
vminm: https://library.oregonstate.edu/floormaps/microforms
vnen: https://library.oregonstate.edu/floormaps/newspapers
vopg: https://library.oregonstate.edu/osu-press-collection
vovg: https://library.oregonstate.edu/floormaps#coll
vrpg: https://library.oregonstate.edu/floormaps/playfile
vrcnc: https://library.oregonstate.edu/floormaps/information-desk
vrdn: https://library.oregonstate.edu/floormaps/information-desk
vrbl: https://library.oregonstate.edu/floormaps/circulation
vrbm: https://library.oregonstate.edu/floormaps/circulation
